version: 2
log-file: /tmp/efm.log
log-level: 4
root-markers:
  - .git/

tools:
  js-prettier: &js-prettier
    format-command: './node_modules/.bin/prettier --stdin-filepath ${INPUT}'
    format-stdin: true
    root-markers:
      - '.prettierrc'
      - '.prettierrc.json'

  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    require-marker: true
    root-markers:
      - .eslintrc.cjs
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json
  
  # yaml-yamllint: &yaml-yamllint
  #   lint-command: 'yamllint -f parsable -'
  #   lint-stdin: true

  # sh-shellcheck: &sh-shellcheck
  #   lint-command: 'shellcheck -f gcc -x'
  #   lint-formats:
  #     - '%f:%l:%c: %trror: %m'
  #     - '%f:%l:%c: %tarning: %m'
  #     - '%f:%l:%c: %tote: %m'

  # vale: &vale
  #   lint-command: 'vale --output=~/.config/vale/output.tmpl '
  #   lint-ignore-exit-code: true
  #   lint-formats:
  #     - '%f:%l:%c:%trror:%m'
  #     - '%f:%l:%c:%tarning:%m'
  #   require-marker: true
  #   root-markers:
  #     - '.vale.ini'

  # dockerfile-hadolint: &dockerfile-hadolint
  #   lint-command: 'hadolint'
  #   lint-formats:
  #     - '%f:%l %m'

  # golangci-lint: &golangci-lint
  #   lint-command: 'golangci-lint run --color never --out-format tab'
  #   lint-stdin: false
  #   lint-ignore-exit-code: true
  #   lint-formats:
  #     - '%f:%l:%c %m'
  #   root-makers:
  #     - .golangci.yml
  #     - .golangci.yaml
  #     - .golangci.toml
  #     - .golangci.json

  goimports: &goimports
    format-command: 'goimports -srcdir ${INPUT}'
    format-stdin: true

  # gofmt: &gofmt
  #   format-command: 'gofmt ${INPUT}'
  #   format-stdin: true

languages:
  javascript:
    - <<: *js-prettier
    - <<: *eslint

  javascriptreact:
    - <<: *js-prettier
    - <<: *eslint

  typescript:
    - <<: *js-prettier
    - <<: *eslint

  typescriptreact:
    - <<: *js-prettier
    - <<: *eslint
  
  html:
    - <<: *js-prettier
  
  css:
    - <<: *js-prettier

  scss:
    - <<: *js-prettier

  json:
    - <<: *js-prettier

  # yaml:
  #   - <<: *yaml-yamllint

  # sh:
  #   - <<: *sh-shellcheck
  #   - <<: *prettier

  markdown:
    # - <<: *vale
    - <<: *js-prettier

  # dockerfile:
  #   - <<: *dockerfile-hadolint

  go:
    # - <<: *golangci-lint
    - <<: *goimports
    # - <<: *gofmt
