version: 2
root-markers:
  - .git/

tools:
  prettier: &prettier
    format-command: 'prettier --stdin-filepath ${INPUT}'
    format-stdin: true
  
  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  javascript:
    - <<: *prettier

  javascriptreact:
    - <<: *prettier

  typescript:
    - <<: *prettier

  typescriptreact:
    - <<: *prettier
  
  yaml:
    - <<: *yaml-yamllint

  sh:
    - <<: *sh-shellcheck
