unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

filetype plugin indent on
syntax on

runtime macros/matchit.vim

set nocompatible
set autoindent
set smartindent
set smarttab
set backspace=indent,eol,start
set hidden
set incsearch
set ruler
set wildmenu
set autoread
set path+=**
set signcolumn=yes
set hidden
set nobackup
set noswapfile
set incsearch hlsearch
set scrolloff=5
set completeopt=menuone,noselect
set mouse=a
set nuw=4
set spelllang=en
set spellsuggest=best,9
set noshowmode
set wildignore+=*.png,*.jpg,*jpg,*/.git/*,*/node_modules/*
set nowrap
set termguicolors
set background=dark
set number
set colorcolumn=100
set showmode

call plug#begin()
Plug 'mattn/emmet-vim'
Plug 'mbbill/undotree'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'tpope/vim-commentary'

Plug 'junegunn/seoul256.vim'
Plug 'gruvbox-community/gruvbox'
Plug 'arzg/vim-colors-xcode'

Plug 'tpope/vim-fugitive'

Plug 'junegunn/fzf.vim'
call plug#end()
" slut for managing indent...
" dispatch for async test runner (can show the results in the qf)
" unpaired for binding stuff

let mapleader=" "
:imap jk <Esc>
nnoremap <leader>s :update<cr>
nnoremap <leader>qq :q<cr>
nnoremap <c-l> :nohl<cr>
nnoremap n nzz
nnoremap N Nzz
nnoremap / ms/
nnoremap ? ms?
nnoremap Y y$

" colorscheme xcodedarkhc

set runtimepath^=~/.fzf

let g:seoul256_background = 252
colo seoul256

nnoremap <leader>ff :Files<cr>

let g:loaded_matchparen = 1
let g:loaded_matchit = 1
let g:loaded_2html_plugin = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_gzip = 1
let g:loaded_logipat = 1
let g:loaded_rrhelper = 1
let g:loaded_tarPlugin = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zipPlugin = 1


" vim:set et sw=2 foldmethod=exp
